-- LearnX baseline schema.
--
-- Authored from the entity model rather than dumped from the previous
-- Hibernate-managed database, so it carries no ddl-auto artefacts. From here
-- on the schema is owned by these migrations and Hibernate only validates it.
--
-- Conventions:
--   * identity primary keys
--   * text for anything free-form; no arbitrary varchar caps
--   * every foreign key has an index, since all of them are filtered on
--   * timestamps are naive local times, matching the LocalDateTime fields

CREATE TABLE universities (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL UNIQUE,
    domain   VARCHAR(255) NOT NULL UNIQUE,
    logo_url TEXT
);

CREATE TABLE student_classes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch         VARCHAR(255),
    department    VARCHAR(255),
    section       VARCHAR(255),
    university_id BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_student_classes_university ON student_classes (university_id);
CREATE INDEX idx_student_classes_lookup ON student_classes (batch, department, section);

-- Every account lives here, platform owners included. The role column is what
-- separates them; university_id is null only for a SYSTEM_ADMIN.
CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(255) NOT NULL UNIQUE,
    password         VARCHAR(255) NOT NULL,
    full_name        VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL UNIQUE,
    role             VARCHAR(32)  NOT NULL,
    approved         BOOLEAN      NOT NULL DEFAULT FALSE,
    id_no            VARCHAR(255),
    department       VARCHAR(255),
    batch            VARCHAR(255),
    semester         VARCHAR(255),
    section          VARCHAR(255),
    designation      VARCHAR(255),
    profile_pic_url  TEXT,
    student_class_id BIGINT REFERENCES student_classes (id),
    university_id    BIGINT REFERENCES universities (id),
    CONSTRAINT chk_users_role
        CHECK (role IN ('STUDENT', 'CR', 'TEACHER', 'ADMIN', 'SYSTEM_ADMIN'))
);
CREATE INDEX idx_users_university ON users (university_id);
CREATE INDEX idx_users_student_class ON users (student_class_id);
-- Supports the pending-approval queue, which filters on both columns.
CREATE INDEX idx_users_approved_university ON users (approved, university_id);

CREATE TABLE courses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(255)     NOT NULL,
    name          VARCHAR(255)     NOT NULL,
    credits       DOUBLE PRECISION NOT NULL,
    semester      VARCHAR(255)     NOT NULL,
    department    VARCHAR(255)     NOT NULL,
    university_id BIGINT           NOT NULL REFERENCES universities (id)
);
CREATE INDEX idx_courses_university ON courses (university_id);

CREATE TABLE class_course_assignments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_class_id BIGINT NOT NULL REFERENCES student_classes (id),
    course_id        BIGINT NOT NULL REFERENCES courses (id),
    teacher_id       BIGINT NOT NULL REFERENCES users (id)
);
CREATE INDEX idx_assignments_class ON class_course_assignments (student_class_id);
CREATE INDEX idx_assignments_course ON class_course_assignments (course_id);
CREATE INDEX idx_assignments_teacher ON class_course_assignments (teacher_id);

CREATE TABLE system_metadata (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(255) NOT NULL,
    meta_value    VARCHAR(255) NOT NULL,
    university_id BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_system_metadata_university_type ON system_metadata (university_id, type);

CREATE TABLE schedule_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week      VARCHAR(32)  NOT NULL,
    start_time       TIME         NOT NULL,
    end_time         TIME         NOT NULL,
    course_name      VARCHAR(255) NOT NULL,
    teacher_name     VARCHAR(255),
    room_no          VARCHAR(255),
    student_class_id BIGINT REFERENCES student_classes (id),
    university_id    BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_schedule_items_class ON schedule_items (student_class_id);
CREATE INDEX idx_schedule_items_university ON schedule_items (university_id);

CREATE TABLE class_tests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name      VARCHAR(255) NOT NULL,
    date_time        TIMESTAMP    NOT NULL,
    duration_minutes INTEGER      NOT NULL DEFAULT 0,
    room_no          VARCHAR(255),
    topic            VARCHAR(255),
    created_by       VARCHAR(255),
    student_class_id BIGINT REFERENCES student_classes (id),
    university_id    BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_class_tests_class_date ON class_tests (student_class_id, date_time);
CREATE INDEX idx_class_tests_university ON class_tests (university_id);

CREATE TABLE exams (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    teacher_id       BIGINT       NOT NULL REFERENCES users (id),
    duration_minutes INTEGER      NOT NULL DEFAULT 0,
    start_time       TIMESTAMP,
    end_time         TIMESTAMP,
    published        BOOLEAN      NOT NULL DEFAULT FALSE,
    student_class_id BIGINT REFERENCES student_classes (id),
    university_id    BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_exams_teacher ON exams (teacher_id);
CREATE INDEX idx_exams_class ON exams (student_class_id);
CREATE INDEX idx_exams_university ON exams (university_id);

CREATE TABLE exam_questions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id        BIGINT      NOT NULL REFERENCES exams (id),
    question_text  TEXT        NOT NULL,
    question_type  VARCHAR(32) NOT NULL,
    points         INTEGER     NOT NULL DEFAULT 0,
    options        TEXT,
    correct_answer VARCHAR(255),
    CONSTRAINT chk_exam_questions_type CHECK (question_type IN ('MCQ', 'SHORT_ANSWER'))
);
CREATE INDEX idx_exam_questions_exam ON exam_questions (exam_id);

CREATE TABLE exam_submissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id      BIGINT    NOT NULL REFERENCES exams (id),
    student_id   BIGINT    NOT NULL REFERENCES users (id),
    submitted_at TIMESTAMP NOT NULL,
    score        INTEGER   NOT NULL DEFAULT 0,
    answers_json TEXT
);
CREATE INDEX idx_exam_submissions_exam ON exam_submissions (exam_id);
CREATE INDEX idx_exam_submissions_student ON exam_submissions (student_id);
-- A student submits an exam once.
CREATE UNIQUE INDEX uq_exam_submissions_exam_student ON exam_submissions (exam_id, student_id);

CREATE TABLE gradebooks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT           NOT NULL REFERENCES users (id),
    course_name     VARCHAR(255)     NOT NULL,
    assessment_name VARCHAR(255)     NOT NULL,
    marks_obtained  DOUBLE PRECISION NOT NULL,
    max_marks       DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_gradebooks_student ON gradebooks (student_id);

-- File bytes live on disk under learnx.storage.root; this row keeps the key.
CREATE TABLE resources (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    course_name      VARCHAR(255) NOT NULL,
    file_name        VARCHAR(255),
    content_type     VARCHAR(255),
    storage_key      VARCHAR(200),
    file_size        BIGINT,
    sha256           VARCHAR(64),
    uploader_id      BIGINT       NOT NULL REFERENCES users (id),
    approved         BOOLEAN      NOT NULL DEFAULT FALSE,
    exam_tags        VARCHAR(255),
    drive_link       VARCHAR(255),
    student_class_id BIGINT REFERENCES student_classes (id),
    university_id    BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_resources_uploader ON resources (uploader_id);
CREATE INDEX idx_resources_university ON resources (university_id);
-- Backs both library listings: approved-by-class and the moderation queue.
CREATE INDEX idx_resources_approved_class ON resources (approved, student_class_id);

CREATE TABLE resource_reactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id   BIGINT       NOT NULL,
    username      VARCHAR(255) NOT NULL,
    reaction_type VARCHAR(32)  NOT NULL,
    CONSTRAINT uq_resource_reactions_resource_user UNIQUE (resource_id, username)
);
CREATE INDEX idx_resource_reactions_resource ON resource_reactions (resource_id);

CREATE TABLE announcements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255)   NOT NULL,
    content          VARCHAR(10000) NOT NULL,
    created_at       TIMESTAMP,
    created_by       VARCHAR(255)   NOT NULL,
    created_by_role  VARCHAR(64)    NOT NULL,
    student_class_id BIGINT REFERENCES student_classes (id),
    university_id    BIGINT REFERENCES universities (id)
);
CREATE INDEX idx_announcements_class ON announcements (student_class_id);
CREATE INDEX idx_announcements_university ON announcements (university_id);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(64)  NOT NULL,
    entity_id   BIGINT,
    action      VARCHAR(32)  NOT NULL,
    changed_by  VARCHAR(255) NOT NULL,
    timestamp   TIMESTAMP    NOT NULL,
    details     TEXT
);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs (timestamp);

CREATE TABLE bug_reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    reported_by VARCHAR(255),
    created_at  TIMESTAMP,
    status      VARCHAR(32)  NOT NULL
);

CREATE TABLE profile_change_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT  NOT NULL REFERENCES users (id),
    new_full_name  VARCHAR(255),
    new_email      VARCHAR(255),
    new_id_no      VARCHAR(255),
    new_department VARCHAR(255),
    new_batch      VARCHAR(255),
    new_semester   VARCHAR(255),
    new_section    VARCHAR(255),
    new_designation VARCHAR(255),
    approved       BOOLEAN NOT NULL DEFAULT FALSE,
    rejected       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP
);
CREATE INDEX idx_profile_change_requests_user ON profile_change_requests (user_id);

CREATE TABLE promotion_history (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_class_id        BIGINT       NOT NULL REFERENCES student_classes (id),
    from_semester           VARCHAR(255) NOT NULL,
    to_semester             VARCHAR(255) NOT NULL,
    timestamp               TIMESTAMP    NOT NULL,
    saved_assignments_json  TEXT
);
CREATE INDEX idx_promotion_history_class ON promotion_history (student_class_id);
