-- The routine stops being typed in and starts being read.
--
-- A university publishes its timetable as a Google Sheet -- one tab per
-- weekday, plus a tab mapping teacher codes to names -- and that sheet is the
-- thing students actually trust. Two tables follow from that: where each
-- department's sheet is, and the changes to it that a class representative
-- announces between publications.
--
-- Every statement here also runs against H2 in PostgreSQL mode, because the
-- test suite applies these same scripts.

-- ---------------------------------------------------------------------------
-- Where a department's routine is published.
-- ---------------------------------------------------------------------------
--
-- Scoped to a department rather than to a university: a faculty of engineering
-- and a faculty of business keep separate timetables, on separate sheets, and
-- neither wants the other's. The row with an empty department is the
-- university's fallback, used by anyone whose department has none of its own.
CREATE TABLE routine_sources (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id BIGINT       NOT NULL,
    -- '' means "the fallback for this university". An empty string rather than
    -- NULL because the unique index below has to cover the fallback too, and
    -- both PostgreSQL and H2 treat NULLs in an index as distinct from each
    -- other -- which would allow any number of fallbacks.
    department    VARCHAR(200) NOT NULL DEFAULT '',
    -- The sheet's id, never a full URL: what is pasted in is reduced to the id
    -- before it is stored, so one department cannot be pointed at a `javascript:`
    -- or a redirector by way of the address bar.
    sheet_id      VARCHAR(120) NOT NULL,
    -- The gid of each weekday tab, in the sheet's own order, comma separated.
    day_gids      VARCHAR(400) NOT NULL,
    -- The tab mapping teacher codes to names. Optional: without it the codes
    -- are shown as they appear in the cells.
    teacher_gid   VARCHAR(40),
    -- Optional hints for merged cells, as JSON: {"SUNDAY":{"6":2}} means the
    -- class in column 6 on Sunday runs for two periods. A sheet that merges
    -- cells reports the merged ones as empty, which is indistinguishable from
    -- a free period, so this cannot be inferred.
    block_hints   TEXT,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(255),
    CONSTRAINT fk_routine_sources_university
        FOREIGN KEY (university_id) REFERENCES universities (id) ON DELETE CASCADE
);

-- One source per department, and exactly one fallback per university.
CREATE UNIQUE INDEX ux_routine_sources_department
    ON routine_sources (university_id, department);

CREATE INDEX ix_routine_sources_university ON routine_sources (university_id);

-- ---------------------------------------------------------------------------
-- What changed since the sheet was published.
-- ---------------------------------------------------------------------------
--
-- A cancelled class is not a personal note; it is news, and the class
-- representative is the one who has it. These rows are posted for a whole
-- class group and every member of it sees them against the sheet.
CREATE TABLE routine_overrides (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id    BIGINT       NOT NULL,
    student_class_id BIGINT       NOT NULL,
    -- The calendar date this applies to. Overrides are always date-specific:
    -- "cancelled on the 14th", never "cancelled on Tuesdays".
    on_date          DATE         NOT NULL,
    -- ADDED or CANCELLED.
    kind             VARCHAR(16)  NOT NULL,
    -- For CANCELLED: which class in the sheet, as "start-end|course", matched
    -- case-insensitively and ignoring spacing. The sheet has no ids of its own,
    -- and a row may move between publications, so this is deliberately a
    -- description rather than a reference.
    target_key       VARCHAR(300),
    course_name      VARCHAR(200),
    room_no          VARCHAR(60),
    teacher_name     VARCHAR(200),
    -- Minutes from midnight, so ordering against the sheet needs no parsing.
    start_minute     INTEGER,
    end_minute       INTEGER,
    note             VARCHAR(400),
    created_by       VARCHAR(255) NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_routine_overrides_university
        FOREIGN KEY (university_id) REFERENCES universities (id) ON DELETE CASCADE,
    CONSTRAINT fk_routine_overrides_class
        FOREIGN KEY (student_class_id) REFERENCES student_classes (id) ON DELETE CASCADE,
    CONSTRAINT chk_routine_overrides_kind CHECK (kind IN ('ADDED', 'CANCELLED'))
);

CREATE INDEX ix_routine_overrides_class_date
    ON routine_overrides (student_class_id, on_date);

-- ---------------------------------------------------------------------------
-- The sheet the seeded university already publishes.
-- ---------------------------------------------------------------------------
--
-- Seeded as the university-wide fallback so the routine screen has something
-- to read on a fresh install, rather than an empty state that can only be
-- fixed by an administrator who does not yet know the screen exists.
INSERT INTO routine_sources (university_id, department, sheet_id, day_gids, teacher_gid, block_hints, updated_at, updated_by)
SELECT u.id,
       '',
       '1vPpOGcZH6LIJ23h3-TM6CnYFYERVfeMzAQ3ImVI_04E',
       '1738789421,1122127138,74242489,551214379,546741780',
       '50237967',
       '{"45(b)":{"SUNDAY":{"6":2,"9":3},"MONDAY":{"3":2,"9":3},"TUESDAY":{"9":2},"WEDNESDAY":{"6":3},"THURSDAY":{"3":3,"6":2}}}',
       CURRENT_TIMESTAMP,
       'system'
FROM universities u
WHERE u.domain = 'ustc.ac.bd';
